version: '3'

services:
  firestorm-db:
    container_name: firestorm-db
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./.docker/firestorm-db:/var/lib/postgresql/data
    networks:
      platform:
        aliases:
          - db

  firestorm:
    container_name: firestorm
    build: .
    ports:
      - 4000:4000
      - 8081:8081
    volumes:
      - '.:/firestorm'
      - '.docker/deps:/firestorm-deps'
      - '.docker/build:/firestorm-build'
      - '.docker/node_modules:/firestorm-node_modules'
    command: bash -c "mix phx.server"
    environment:
      NODE_PATH: /firestorm-node_modules
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST: 'db'
      POSTGRES_PORT: 5432
    depends_on:
      - firestorm-db
    networks:
      platform:
        aliases:
          - firestorm

networks:
  platform:

